apiVersion: apps/v1
kind: Deployment
metadata:
  name: appweb
spec:
  selector:
    matchLabels:
      app: appweb
  template:
    metadata:
      labels:
        app: appweb
    spec:
      containers:
      - name: appweb
        image: davicarneiro/appweb:{{tag}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appweb
spec:
  selector:
    app: appweb
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
