name: CI/CD para Docker Hub e Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código-fonte
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         run: |
          docker build -t web-app:latest .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker tag web-app:latest web-app:1.0
          docker push web-app:latest
          docker push web-app:1.0

    - name: Configurar Kubeconfig
      run: |
        echo ${{ secrets.KUBE_CONFIG_DATA }} | base64 -d > kubeconfig.yaml

    - name: Deploy no Kubernetes
      run: |
        kubectl --kubeconfig=kubeconfig.yaml apply -f ../deployment.yaml
