name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código-fonte
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         run: |
          docker build -t web-app:latest .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker tag web-app:latest web-app:1.0
          docker push web-app:latest
          docker push web-app:1.0      


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Código
  #       uses: actions/checkout@v2

  #     - name: Configurar kubectl
  #       run: |
  #         aws eks --region us-east-1 update-kubeconfig --name imersao-eks
  #         kubectl config use-context imersao-eks

  #     - name: Aplicar manifestos no Kubernetes
  #       run: |
  #        kubectl apply -f ./k8s/deployment.yaml

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS CLI
      run: |
        echo ${{ secrets.AWS_ACCESS_KEY_ID }} >> AKIASDCTPFJHBBIIIQRC
        echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> 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
        aws configure set aws_access_key_id $(cat aws_access_key)
        aws configure set aws_secret_access_key $(cat aws_secret_key)
        rm aws_access_key aws_secret_key

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
  