name: Docker Build, Push, e Kubernetes Deploy

on:
   push:
     branches:
       - main
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Docker meta
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           images: davicarneiro/app-web
           tag-sha: true
    
       - name: QEMU
         uses: docker/setup-qemu-action@v1
        
       - name: Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
