name: Docker Build, Push, e Kubernetes Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: davicarneiro/app-web
          tag-sha: true
      
      - name: QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{steps.docker_meta.outputs.tags}}
          labels: ${{steps.docker_meta.outputs.labels}}
            
           # ${{ steps.docker_meta.outputs.tags }}
           # ${{ secrets.DOCKERHUB_USERNAME }}/app-web:latest
        
  deploy-to-kubernetes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Código
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Configurar Kubeconfig
      run: aws eks --region us-east-1 update-kubeconfig --name imersao-eks

    - name: Aplicar Configurações do Kubernetes
      run: kubectl apply -f ./k8s/deployment.yaml

    - name: Atualizar Imagem do Contêiner (se necessário)
      run: |
        kubectl set image deployment/app-web app-web=${{ secrets.DOCKERHUB_USERNAME }}/app-web:${{ secrets.DOCKERHUB_USERNAME }}