name: CI/CD para Docker Hub e Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código-fonte
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: |
         davicarneiro/web-app

    - name: Build and push Docker images
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels 

    # - name: Construir a imagem Docker
    #   run: docker build -t web-app:latest .

    # - name: Fazer push da imagem para o Docker Hub
    #   run: docker push web-app:latest

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Configurar o Kubernetes
  #     uses: azure/k8s-set-context@v1
  #     with:
  #       kubeconfig: ${{ secrets.KUBE_CONFIG }}
  #       namespace: defaul

  #   - name: Aplicar as configurações no Kubernetes
  #     run: kubectl apply -f k8s/deployment.yaml
