name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app-web:latest    

  deploy:
    runs-on: ubuntu-latest

   steps:
    - name: Instalação do kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    steps:
    - name: Checkout Código
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Configurar Kubeconfig
      run: aws eks --region us-east-1 update-kubeconfig --name imersao-eks

    - name: Aplicar Configurações do Kubernetes
      run: kubectl apply -f ./k8s/deployment.yaml

    # - name: Atualizar Imagem do Contêiner (se necessário)
    #   run: |
    #     kubectl set image deployment/seu-deployment seu-container=seu-repo-docker:latest