name: Pipeline AWS Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Login no AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'false'

      - name: Build da aplicação
        run: |
          docker build -t phibro-teste-app .
          echo ${{ steps.login-ecr.outputs.registry }}
          docker tag phibro-teste-app:latest ${{ steps.login-ecr.outputs.registry }}/phibro-teste-app:latest

      - name: Push no ECR
        id: push-ecr
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/phibro-teste-app:latest
          echo "::set-output name=image::${{ steps.login-ecr.outputs.registry }}/phibro-teste-app:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure o Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Aplicar manifestos no Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml



  # test:
  #   needs: deploy-eks
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Executar testes
  #       run: |
  #         # Coloque aqui os comandos para executar seus testes




# name: CI/CD para ECR e Kubernetes

# on:
#   push:
#     branches:
#       - main # Troque para a branch que deseja usar

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Verificar código
#       uses: actions/checkout@v2

#     - name: Login no Amazon ECR
#       id: login-ecr
#       run: |
#         echo ${{ secrets.AWS_ACCESS_KEY_ID }} | aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login -u AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
#       env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: ${{ secrets.AWS_REGION }}
#         AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}


#     - name: Build da imagem Docker
#       run: |
#         docker build -t phibro-teste-app:latest .
#         docker tag phibro-teste-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/phibro-teste-app:latest
#       working-directory: ./src


#     - name: Push da imagem para o ECR
#       run: |
#         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/phibro-teste-app:latest
#       working-directory: ./src

#     - name: Configurar Kubectl
#       run: |
#         aws eks update-kubeconfig --name phibro-testes-eks --region ${{ secrets.AWS_REGION }}
#       env:
#         KUBECONFIG: ${{ runner.workspace }}/kubeconfig

#     - name: Aplicar manifestos do Kubernetes
#       run: |
#         kubectl apply -f ./k8s/deployment.yaml
#       env:
#         KUBECONFIG: ${{ runner.workspace }}/kubeconfig

